project:
  type: website

website:
  title: "방태모의 블로그"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Blog
format:
  html:
    theme: my-litera.scss
    css: styles.css
    toc: true
    # comments:
    #   giscus:
    #     repo: joelnitta/joelnitta-home
    #     repo-id: R_kgDOGZGr3w
    #     category: Comments
    #     category-id: DIC_kwDOGZGr384B_-52
    #     mapping: pathname
    #     reactions-enabled: True
    #     input-position: top
    #     theme: light
    #     language: en
    # include-in-header: header.html

editor: visual

