project:
  type: website
  output-dir: _site
  preview:
    port: 5902
    browser: false
    
website:
  title: "방태모의 블로그"
  description: "방태모의 개인 블로그입니다."
  favicon: images/favicon.png
  google-analytics: "G-1QHE9697JG"
  cookie-consent: true
  navbar:
    right:
      - href: index.qmd
        text: 홈
      - href: blog.qmd
        text: 블로그
      - href: archive.qmd
        text: 아카이브

format:
  html:
    toc: true
    theme:
      light: css/karat_quarto.scss
      dark: css/karat_dark.scss
    code-copy: true
    code-overflow: wrap
    css: css/karat.css