project:
  type: website

website:
  title: "방태모의 블로그"
  description: "방태모의 개인 블로그입니다."
  favicon: images/favicon.png
  site-url: https://quarto-taemo.netlify.app
  repo-url: https://github.com/be-favorite/Blog
  repo-actions: [issue]
  reader-mode: true
  page-footer: 
    left: "Copyright 2022, Taemo Bang" 
    right: 
      - icon: linkedin
        href: https://www.linkedin.com/in/taemo/
      - icon: facebook
        href: https://www.facebook.com/profile.php?id=100070120780059
      - icon: twitter
        href: https://twitter.com/TaemoBang
      - icon: github
        href: https://github.com/be-favorite
  navbar:
    right:
      - href: index.qmd
        text: 홈
      - href: blog.qmd
        text: 블로그
      - href: archive.qmd
        text: 아카이브
      - text: 리소스
        menu: 
          - text: 연구 아카이브
            href: research.qmd
          - text: 발표 아카이브
            href: presentation.qmd
        
# google-analytics:
cookie-consent: TRUE

format:
  html:
    toc: true
    theme:
      light: css/karat_quarto.scss
      dark: css/karat_dark.scss
    code-copy: true
    code-overflow: wrap
    css: css/karat.css
    comments:
      giscus:
        repo: be-favorite/Blog
        repo-id: R_kgDOH0qA6g
        category: Comments
        category-id: DIC_kwDOH0qA6s4CReuX
        mapping: pathname
        reactions-enabled: true
        input-position: top
        theme: light
        language: ko