project:
  type: website
  output-dir: _site
  preview:
    port: 5902
    browser: false
    
website:
  title: "방태모의 블로그"
  description: "방태모의 개인 블로그입니다."
  favicon: images/favicon.png
  site-url: https://taemobang.com
  repo-url: https://github.com/be-favorite/Blog
  repo-actions: [issue]
  navbar:
    right:
      - href: index.qmd
        text: 홈
      - href: blog.qmd
        text: 블로그
      - href: archive.qmd
        text: 아카이브
      - text: 리소스
        menu: 
          - text: 연구 아카이브
            href: research.qmd
          - text: 발표 아카이브
            href: presentation.qmd
        
google_analytics: "G-1QHE9697JG"
cookie-consent: TRUE

format:
  html:
    toc: true
    theme:
      light: css/karat_quarto.scss
      dark: css/karat_dark.scss
    code-copy: true
    code-overflow: wrap
    css: css/karat.css
    comments:
      giscus:
        repo: be-favorite/Blog
        repo-id: R_kgDOH0qA6g
        category: Comments
        category-id: DIC_kwDOH0qA6s4CReuX
        mapping: pathname
        reactions-enabled: true
        input-position: top
        theme: light
        language: ko