project:
  type: website

website:
  title: "방태모의 블로그"
  favicon: images/favicon.png
  site-url: https://quarto-taemo.netlify.app
  repo-url: https://github.com/be-favorite/Blog
  description: "방태모의 개인 블로그입니다."
  navbar:
    right:
      - href: index.qmd
        text: 홈
      - href: blog.qmd
        text: 블로그
      - href: archive.qmd
        text: 아카이브
        
# google-analytics:
cookie-conset: TRUE

format:
  html:
    toc: true
    theme:
      light: css/karat_quarto.scss
      dark: css/karat_dark.scss
    code-copy: true
    code-overflow: wrap
    css: css/karat.css
    comments:
      giscus:
        repo: be-favorite/Blog
        repo-id: R_kgDOH0qA6g
        category: Comments
        category-id: DIC_kwDOH0qA6s4CReuX
        mapping: pathname
        reactions-enabled: true
        input-position: top
        theme: light
        language: en