project:
  type: website

website:
  title: "방태모의 블로그"
  favicon: images/favicon.png
  site-url: https://taemobang.com/
  repo-url: https://github.com/be-favorite/Blog
  navbar:
    right:
      - href: index.qmd
        text: 홈
      - href: blog.qmd
        text: 블로그
      - href: archive.html
        text: 아카이브
      - href: https://taemobang.notion.site
        text: 이력서
format:
  html:
    theme: my-litera.scss
    css: styles.css
    toc: true
    # comments:
    #   giscus:
    #     repo: joelnitta/joelnitta-home
    #     repo-id: R_kgDOGZGr3w
    #     category: Comments
    #     category-id: DIC_kwDOGZGr384B_-52
    #     mapping: pathname
    #     reactions-enabled: True
    #     input-position: top
    #     theme: light
    #     language: en
    # include-in-header: header.html

editor: visual

