---
title: "발표 아카이브"
page-layout: full
comments: false
---

발표자료와 강의자료를 아카이브합니다.

Github: [be-favorite/Presentation_archive](https://github.com/be-favorite/Presentation_archive)

| Tag                                                    | 제목                                                                                                                                                                | 설명                                                                                                                                                                                                                                                                                               | 이벤트                                                                                                                  | 날짜         | 장소                                                                                      |
| ------------------------------------------------------ | ----------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | -------------------------------------------------------------------------------------------------------------------- | ---------- | --------------------------------------------------------------------------------------- |
| Experimentation                                        | [온라인 통제 실험의 모범 사례](https://be-favorite.github.io/Presentation_archive/materials/Korea%20Summer%20Workshop%20ln%20Causal%20Inference_2024_OCEs_Best_Practices.pdf) | A/B 실험의 신뢰도를 보장하기 위해 실험의 라이프사이클 전반에 걸쳐 고려해야할 사항 ([발표 Q&A](https://github.com/be-favorite/Presentation_archive/wiki/%5BQ&A%5D-2024-Korea-Summer-Workshop-ln-Causal-Inference--%EC%98%A8%EB%9D%BC%EC%9D%B8-%ED%86%B5%EC%A0%9C-%EC%8B%A4%ED%97%98%EC%9D%98-%EB%AA%A8%EB%B2%94-%EC%82%AC%EB%A1%80-)) | [2024 Korea Summer Workshop In Causal Inference](https://sites.google.com/view/causal-inference2024/home?authuser=0) | 2024-06-13 | Zoom, [Youtube](https://youtu.be/zcZ2vICGm1o?si=dhgNg2l8yn7EkRM2)                       |
| Experimentation, Power Analysis                        | [실험에 기반한 당신의 가설 검정 결과를 신뢰할 수 없는 이유](https://be-favorite.github.io/Presentation_archive/materials/Datayanolja_2024_Power_Analysis.pdf)                             | 수식을 최대한 배제하고 그림을 기반으로 최대한 쉽게 검정력 분석의 본질을 설명하고, 검정력 분석을 둘러싼 오해를 풀고자 함                                                                                                                                                                                                                             | [데이터야놀자 2024](https://datayanolja.kr/)                                                                               | 2024-06-01 | 광화문 마이크로소프트 오피스, [Youtube](https://youtu.be/1jTn9b3_-u0?si=GezPKKXeI04gkbTS)            |
| Experimentation, Delta Method, Mathematical Statistics | [CTR의 분산 추정 중 빠질 수 있는 함정](https://be-favorite.github.io/Presentation_archive/materials/Pseudolab_Pifalls_Variance_Estimation_Ratio_Metrics.pdf)                   | 비율 지표의 정확한 분산 추정을 위한 Delta method 기법 소개                                                                                                                                                                                                                                                          | 가짜연구소 인과추론 팀 행사                                                                                                      | 2024-05-25 | 삼성동 op.gg 사옥                                                                            |
| Experimentation, Statstics                             | [온라인 통제 실험 소개 및 분석 기초](https://be-favorite.github.io/Presentation_archive/materials/Introduction_to_OCEs.pdf)                                                     | <[실무로 통하는 인과추론 with 파이썬](https://product.kyobobook.co.kr/detail/S000212577153)> 교재 Chapter 2 특강                                                                                                                                                                                                  | 인과추론의 데이터 과학 [실무로 통하는 인과추론]                                                                                          | 2024-05-19 | [Youtube](https://youtu.be/FYTPUnBl-lQ?si=Ww9v_JwkXUbpBjtc)                             |
| Experimentation                                        | 신뢰할 수 있는 온라인 통제 실험의 기초 및 분석 가이드                                                                                                                                   | 실험 플랫폼 런칭 후, 실험 오너가 되어 실험 분석을 수행할 수도 있는 분들을 위한 온라인 통제 실험 가이드                                                                                                                                                                                                                                     | G마켓 테크캠퍼스                                                                                                            | 2024-02-28 | Zoom                                                                                    |
| Experimentation, A/A Test                              | [당신의 A/B Test를 신뢰할 수 없는 이유](https://be-favorite.github.io/Presentation_archive/Datayanolja_2023_Trustworthy_ABtest.pdf)                                           | 신뢰도 높은 실험을 위해 우리가 인식해야 할 것들, 우리가 모르고 지나칠 수 있는 함정을 발견할 수 있는 방법                                                                                                                                                                                                                                    | [데이터야놀자 2023](https://datayanolja.kr/)                                                                               | 2023-10-15 | 역삼 센터필드 EAST 18F AWS Korea, [Youtube](https://youtu.be/J4zjwJNYyPM?si=TFYm01c1hDr1rYeL) |
| Visualization, R                                       | [ggplot2 컬러링 가이드](https://be-favorite.github.io/Presentation_archive/coloring_guide/coloring_guide.html#1)                                                        | 적은 수의 컬러로 직관적인 시각화를 수행하는 방법                                                                                                                                                                                                                                                                      | 서울 R 미트업                                                                                                             | 2022-08-12 | 건국대학교 상허연구관                                                                             |
| Time Series, Regression                                | [DLNM을 이용한 대기오염원 건강영향평가](https://be-favorite.github.io/Presentation_archive/kdca_dlnm/kdca_dlnm.html#1)                                                           | 연구 방법론 소개 및 R 실습                                                                                                                                                                                                                                                                                 | 질병관리청 건강보험 청구자료 데이터 교육                                                                                               | 2022-07-11 | 가천대학교 의과대학                                                                              |
| Causal Inference                                       | [통계실습 III. 매칭](https://be-favorite.github.io/Presentation_archive/3_matching/3_matching.html#1)                                                                   | 매칭과 Weighting 기초 및 R 실습                                                                                                                                                                                                                                                                          | 가천대 길병원 고급통계교육                                                                                                       | 2022-06-28 | 가천대학교 의과대학                                                                              |
| Survival Analysis                                      | [통계실습 II. 생존분석](https://be-favorite.github.io/Presentation_archive/2_survival/2_survival.html#1)                                                                  | 생존분석 기초 및 R 실습                                                                                                                                                                                                                                                                                   | 가천대 길병원 고급통계교육                                                                                                       | 2022-06-21 | 가천대학교 의과대학                                                                              |
| Time Series, Regression                                | [통계실습 I. 회귀분석, ARIMA 모형](https://be-favorite.github.io/Presentation_archive/1_regression_arima/1_regression_arima.html#1)                                         | 회귀분석과 ARIMA 모형 기초 및 R 실습                                                                                                                                                                                                                                                                         | 가천대 길병원 고급통계교육                                                                                                       | 2022-06-14 | 가천대학교 의과대학                                                                              |
| Time Series, Regression                                | [Introduction to DLM and DLNM](https://be-favorite.github.io/Presentation_archive/DLM%2C%20DLNM/Introduction_dlm%2Cdlnm.html#1)                                   | Distributed lad model과 Distributed lag non-linear model 소개                                                                                                                                                                                                                                       | 학술연구 과제 연구진 회의                                                                                                       | 2021-06-21 | Zoom                                                                                    |